import Link from "next/link"; import { db } from "@/lib/db";
export const revalidate = 300;
const proof = ["Custom manufacturing", "Made in Bangladesh", "Sampling before production", "Artwork-to-delivery support"];
const ORDER = ["hero","proof","products","spotlight","clients","process","cta"];
const D = { headline: "Trims made to carry your brand.", sub: "Woven and printed labels, hang tags, patches and custom trims, manufactured in Bangladesh for apparel brands and buyers.", cta1Label: "Explore products", cta1Url: "/products", cta2Label: "Request a quote", cta2Url: "/request-a-quote", closing: "Tell us what you need. We'll quote it." };
export default async function Home() {
  const [cfg, cats, steps, spot, clients] = await Promise.all([
    db.pageContent.findUnique({ where: { key: "home" } }),
    db.category.findMany({ where: { status: "PUBLISHED", parentId: null }, orderBy: { sortOrder: "asc" }, take: 9 }),
    db.processStep.findMany({ where: { kind: "order" }, orderBy: { sortOrder: "asc" } }),
    db.product.findFirst({ where: { status: "PUBLISHED", featured: true }, include: { category: true, images: { include: { media: true }, orderBy: { sortOrder: "asc" }, take: 3 } } }),
    db.client.findMany({ where: { published: true }, orderBy: { sortOrder: "asc" }, take: 12 }),
  ]);
  const d = (cfg?.data ?? {}) as { sections?: { id: string; enabled: boolean }[]; hero?: Partial<typeof D> }; const h = { ...D, ...d.hero };
  const sections = d.sections?.length ? d.sections : ORDER.map(id => ({ id, enabled: true }));
  const R: Record<string, React.ReactNode> = {
    hero: <section key="hero" className="max-w-7xl mx-auto px-6 pt-20 pb-24 grid lg:grid-cols-[1.3fr_1fr] gap-12 items-center"><div><h1 className="text-[clamp(3rem,8vw,7.5rem)] font-semibold leading-[0.92] tracking-tight">{h.headline}</h1><p className="mt-8 max-w-lg text-lg text-stone">{h.sub}</p>
      <div className="mt-10 flex flex-wrap gap-3"><Link href={h.cta1Url} className="rounded-full border border-ink px-7 py-3.5 font-semibold hover:bg-ink hover:text-paper transition-colors">{h.cta1Label}</Link><Link href={h.cta2Url} className="rounded-full bg-yc px-7 py-3.5 font-semibold hover:bg-ink hover:text-yc transition-colors">{h.cta2Label}</Link></div></div>
      <div aria-hidden className="relative h-96 hidden lg:block"><div className="absolute right-0 top-0 w-72 h-40 bg-yc border-2 rounded-2xl border-dashed border-ink m-2"/><div className="absolute left-4 top-24 w-72 h-44 bg-ink border-2 rounded-2xl border-dashed border-yc m-2"/><div className="absolute right-10 bottom-0 w-60 h-32 bg-paper border-2 rounded-2xl border-dashed border-ink m-2"/></div></section>,
    proof: <section key="proof" aria-label="Highlights" className="border-y border-line"><ul className="max-w-7xl mx-auto px-6 grid grid-cols-2 md:grid-cols-4 divide-x divide-line">{proof.map(p => <li key={p} className="py-5 px-4 text-sm font-semibold">{p}</li>)}</ul></section>,
    products: <section key="products" className="max-w-7xl mx-auto px-6 pt-24"><h2 className="text-4xl md:text-6xl font-semibold tracking-tight max-w-3xl">Built to complete the brand.</h2>{cats.length === 0 ? <p className="mt-8 text-stone">No categories published yet.</p> :
      <ul className="mt-12 grid md:grid-cols-4 gap-4">{cats.map((c, i) => <li key={c.id} className={`rounded-2xl border border-line bg-white overflow-hidden ${i % 5 === 0 ? "md:col-span-2 md:row-span-2 min-h-80" : "min-h-44"}`}><Link href={`/products/${c.slug}`} className="group flex h-full flex-col justify-between p-6 hover:bg-yc transition-colors"><span className="text-2xl md:text-3xl font-bold">{c.name}</span><span className="flex items-end justify-between gap-4 text-sm text-stone group-hover:text-ink"><span>{c.description}</span><span aria-hidden className="text-2xl transition-transform group-hover:translate-x-1">→</span></span></Link></li>)}</ul>}</section>,
    spotlight: spot ? <section key="spotlight" className="max-w-7xl mx-auto px-6 pt-24 grid md:grid-cols-2 gap-10 items-center"><div className="grid grid-cols-3 gap-2">{spot.images.map((im, i) => <img key={im.id} src={im.media.url} alt={im.media.alt} loading="lazy" className={`object-cover w-full ${i === 0 ? "col-span-3 aspect-[4/3]" : "aspect-square"}`}/>)}</div><div><p className="text-sm text-stone">{spot.category.name}</p><h2 className="mt-2 text-4xl font-semibold">{spot.name}</h2><p className="mt-4 text-stone">{spot.shortDescription}</p><Link href={`/products/${spot.category.slug}/${spot.slug}`} className="mt-6 inline-block rounded-full border border-ink px-6 py-3 font-semibold">Explore product</Link></div></section> : null,
    clients: clients.length ? <section key="clients" className="max-w-7xl mx-auto px-6 pt-24"><h2 className="text-sm text-stone">Trusted by</h2><ul className="mt-6 flex flex-wrap items-center gap-x-12 gap-y-6">{clients.map(c => <li key={c.id}>{c.logoUrl ? <img src={c.logoUrl} alt={c.name} loading="lazy" className="h-10 w-auto grayscale opacity-70"/> : <span className="font-bold text-stone">{c.name}</span>}</li>)}</ul></section> : null,
    process: steps.length ? <section key="process" className="max-w-7xl mx-auto px-6 pt-24"><h2 className="text-4xl md:text-6xl font-semibold tracking-tight">From brief to delivery.</h2><ol className="mt-12 grid md:grid-cols-4 gap-x-8 gap-y-10">{steps.map((s, i) => <li key={s.id} className="border-t-4 border-ink pt-4"><span className="text-3xl font-semibold text-yc [-webkit-text-stroke:1px_#0a0a0a]">{String(i + 1).padStart(2, "0")}</span><h3 className="mt-2 font-bold">{s.title}</h3>{s.body && <p className="text-sm text-stone mt-1">{s.body}</p>}</li>)}</ol></section> : null,
    cta: <section key="cta" className="max-w-7xl mx-auto px-6 pt-24"><div className="rounded-3xl bg-ink text-paper p-10 md:p-16 flex flex-col md:flex-row md:items-center justify-between gap-8"><h2 className="text-3xl md:text-5xl font-semibold max-w-xl">{h.closing}</h2><Link href="/request-a-quote" className="rounded-full bg-yc text-ink px-8 py-4 font-semibold self-start">Request a quote</Link></div></section>,
  };
  return <main>{sections.filter(s => s.enabled).map(s => R[s.id])}</main>;
}
